<?php
/**
 * Translation script to convert all English text to Serbian Latin
 */

$translations = [
    // Admin Menu & Navigation
    'Settings' => 'Podešavanja',
    'General Settings' => 'Opšte Postavke',
    'VIP Codes' => 'VIP Kodovi',  
    'Packages' => 'Paketi',
    'Product Settings' => 'Podešavanja Proizvoda',
    'Products' => 'Proizvodi', 
    'Reports' => 'Izveštaji',
    'VIP Settings' => 'VIP Podešavanja',
    'Package Settings' => 'Podešavanja Paketa',
    'Integration Settings' => 'Podešavanja Integracija',
    
    // Common Actions & Labels
    'Edit' => 'Izmeni',
    'Delete' => 'Obriši',
    'Save' => 'Sačuvaj',
    'Cancel' => 'Otkaži',
    'Apply' => 'Primeni',
    'Search' => 'Pretraži',
    'Filter' => 'Filter',
    'Add' => 'Dodaj',
    'View' => 'Prikaži',
    'Active' => 'Aktivni',
    'Inactive' => 'Neaktivni', 
    'Status' => 'Status',
    'Actions' => 'Akcije',
    'Name' => 'Naziv',
    'Price' => 'Cena',
    'Total' => 'Ukupno',
    'Continue' => 'Nastavi',
    'Back' => 'Nazad',
    'Select' => 'Izaberi',
    'Remove' => 'Ukloni',
    'Clear All' => 'Obriši Sve',
    'Select All' => 'Izaberi Sve',
    'Deselect All' => 'Poništi Izbor Svega',
    'Loading...' => 'Učitavam...',
    'Success!' => 'Uspeh!',
    'Error' => 'Greška',
    
    // VIP Related
    'VIP Member' => 'VIP Član', 
    'VIP Price' => 'VIP Cena',
    'Regular Price' => 'Redovna Cena',
    'VIP Discount' => 'VIP Popust',
    'Regular Discount' => 'Redovan Popust',
    'VIP Benefits' => 'VIP Pogodnosti',
    'Enable VIP Pricing' => 'Uključi VIP Cene',
    'Enable VIP Role' => 'Uključi VIP Ulogu',
    'VIP Price Label' => 'VIP Oznaka Cene',
    'Non-VIP Display Format' => 'Format Prikaza za Ne-VIP',
    'Enable Checkout VIP Codes' => 'Uključi VIP Kodove na Naplati',
    'Auto-register with VIP codes' => 'Auto-registruj sa VIP kodovima',
    'Enable Email Notifications' => 'Uključi Email Obaveštenja',
    'Enable Woodmart Integration' => 'Uključi Woodmart Integraciju',
    'Enable Packages' => 'Uključi Pakete',
    
    // Package Related
    'Configure Your Package' => 'Podesi Svoj Paket',
    'Select Your Products' => 'Izaberi Svoje Proizvode', 
    'Package Summary' => 'Rezime Paketa',
    'Add to Cart' => 'Dodaj u Korpu',
    'Package Configuration' => 'Podešavanje Paketa',
    'Allowed Products' => 'Dozvoljeni Proizvodi',
    'Discount Rules' => 'Pravila Popusta',
    'VIP Package' => 'VIP Paket',
    'VIP Packages' => 'VIP Paketi',
    'Add New Package' => 'Dodaj Novi Paket',
    'Edit Package' => 'Izmeni Paket',
    'New Package' => 'Novi Paket',
    'View Package' => 'Prikaži Paket',
    'Search Packages' => 'Pretraži Pakete',
    'No packages found' => 'Nema pronađenih paketa',
    'No packages found in trash' => 'Nema pronađenih paketa u korpi',
    'Package Details' => 'Detalji Paketa',
    'Choose Package Size' => 'Izaberi Veličinu Paketa',
    'Products to select:' => 'Proizvodi za izbor:',
    'Your discount:' => 'Tvoj popust:',
    'VIP bonus discount:' => 'VIP bonus popust:',
    
    // Product Related  
    'No products found. Please create some WooCommerce products first.' => 'Nema pronađenih proizvoda. Molimo kreiiraj prvo neke WooCommerce proizvode.',
    'Create Product' => 'Kreiraj Proizvod',
    'Product Overview' => 'Pregled Proizvoda',
    'Total Products' => 'Ukupno Proizvoda',
    'VIP Pricing Enabled' => 'VIP Cene Uključene',
    'Package Allowed' => 'Paket Dozvoljen',
    'Search products...' => 'Pretraži proizvode...',
    'Enable VIP Pricing' => 'Uključi VIP Cene',
    'VIP Price:' => 'VIP Cena:',
    'Allow in Packages' => 'Dozvoli u Paketima',
    'Edit Product' => 'Izmeni Proizvod',
    'Regular:' => 'Redovna:',
    'VIP:' => 'VIP:',
    'Save %s' => 'Uštedi %s',
    'Save %s (%s%%)' => 'Uštedi %s (%s%%)',
    'Upgrade to VIP for special pricing' => 'Unapredni na VIP za specijalne cene',
    'Product settings updated successfully.' => 'Podešavanja proizvoda su uspešno ažurirana.',
    'Configure VIP pricing and package availability for your products.' => 'Podesi VIP cene i dostupnost paketa za svoje proizvode.',
    
    // Cart & Checkout
    'Package Added to Cart!' => 'Paket Dodat u Korpu!',
    'Your custom package has been successfully added to your cart.' => 'Tvoj prilagođeni paket je uspešno dodat u korpu.',
    'View Cart' => 'Prikaži Korpu',
    'Proceed to Checkout' => 'Nastavi na Naplatu',
    'Continue Shopping' => 'Nastavi sa Kupovinom', 
    'Adding Package to Cart...' => 'Dodavanje Paketa u Korpu...',
    'Please wait while we process your package selection.' => 'Molimo sačekaj dok obrađujemo tvoj izbor paketa.',
    'Error Adding Package' => 'Greška pri Dodavanju Paketa',
    'There was an error adding your package to the cart. Please try again.' => 'Došlo je do greške pri dodavanju paketa u korpu. Molimo pokušaj ponovo.',
    'Try Again' => 'Pokušaj Ponovo',
    'Cart Summary' => 'Rezime Korpe',
    'Cart Total:' => 'Ukupno u Korpi:',
    'Checkout' => 'Naplata',
    
    // VIP Account & Status
    'VIP Membership Status' => 'Status VIP Članstva',
    'Member since %s' => 'Član od %s',
    'Active VIP Member' => 'Aktivni VIP Član',
    'Membership Type:' => 'Tip Članstva:',
    'WooCommerce Memberships' => 'WooCommerce Članstva',
    'WooCommerce Subscriptions' => 'WooCommerce Pretplate', 
    'VIP Code' => 'VIP Kod',
    'Manual Assignment' => 'Ručna Dodela',
    'VIP Role' => 'VIP Uloga',
    'VIP Code Used:' => 'Korišćen VIP Kod:',
    'Your VIP Benefits:' => 'Tvoje VIP Pogodnosti:',
    'Special pricing on VIP products' => 'Specijalne cene na VIP proizvode',
    'Additional discounts on package deals' => 'Dodatni popusti na paket ponude',
    'Priority access to new products' => 'Prioritetni pristup novim proizvodima',
    'Exclusive VIP-only offers and promotions' => 'Ekskluzivne ponude i promocije samo za VIP',
    'VIP Savings Summary:' => 'Rezime VIP Ušteda:',
    'Total Saved' => 'Ukupno Uštedeno',
    'VIP Orders' => 'VIP Narudžbe',
    'Packages Purchased' => 'Kupljeni Paketi',
    'Regular Member' => 'Redovan Član',
    'Upgrade to VIP for exclusive benefits' => 'Unapredi na VIP za ekskluzivne pogodnosti',
    'VIP Membership Benefits:' => 'Pogodnosti VIP Članstva:',
    'Have a VIP Code?' => 'Imaš VIP Kod?',
    'Enter your VIP code' => 'Unesi svoj VIP kod',
    'Activate' => 'Aktiviraj',
    'Please enter a VIP code.' => 'Molimo unesi VIP kod.',
    'Activating...' => 'Aktiviram...',
    'VIP code activated successfully! Please refresh the page.' => 'VIP kod uspešno aktiviran! Molimo osveži stranicu.',
    'Invalid or expired VIP code.' => 'Neispravan ili istekli VIP kod.',
    'Error activating VIP code. Please try again.' => 'Greška pri aktiviranju VIP koda. Molimo pokušaj ponovo.',
    'Contact Us for VIP Access' => 'Kontaktiraj Nas za VIP Pristup',
    'VIP Membership Inquiry' => 'Upit o VIP Članstvu',
    
    // Messages & Notifications  
    'Are you sure you want to delete this item?' => 'Da li ste sigurni da želite da obrišete ovaj element?',
    'An error occurred. Please try again.' => 'Došlo je do greške. Molimo pokušajte ponovo.',
    'Operation completed successfully.' => 'Operacija je uspešno završena.',
    'Configure general plugin settings.' => 'Podesi opšte postavke plugin-a.',
    'Configure VIP membership and pricing settings.' => 'Podesi VIP članstvo i postavke cena.',
    'Configure package system settings.' => 'Podesi postavke sistema paketa.',
    'Configure integration with other plugins and themes.' => 'Podesi integraciju sa drugim plugin-ima i temama.',
    'WooCommerce is required for this plugin to work.' => 'WooCommerce je potreban da bi ovaj plugin radio.',
    'Package post type is not registered. Please activate the plugin properly.' => 'Package post type nije registrovan. Molimo aktiviraj plugin pravilno.',
    'No products are currently enabled for packages. Please configure products in the Product Settings page.' => 'Trenutno nisu omogućeni proizvodi za pakete. Molimo podesi proizvode na stranici Podešavanja Proizvoda.',
    'Configure Products' => 'Podesi Proizvode',
    
    // Pricing & Discounts
    'Subtotal:' => 'Međuzbir:',
    'Package Discount:' => 'Popust za Paket:',
    'VIP Additional Discount:' => 'VIP Dodatni Popust:',
    'Total Savings:' => 'Ukupna Ušteda:',
    'Package Total:' => 'Ukupno za Paket:',
    'Upgrade to VIP and save even more!' => 'Unapredi na VIP i uštedi još više!',
    'With VIP membership, you could save an additional' => 'Sa VIP članstvom, mogao bi da uštediš dodatnih',
    'on this package!' => 'na ovom paketu!',
    'Learn More About VIP' => 'Saznaj Više o VIP',
    'Back to Selection' => 'Nazad na Izbor',
    'Save for Later' => 'Sačuvaj za Kasnije',
    
    // Form & Input Labels
    'Email' => 'Email',
    'Code' => 'Kod', 
    'Domain' => 'Domen',
    'Max Uses' => 'Maks. Korišćenja',
    'Current Uses' => 'Trenutna Korišćenja',
    'Expires' => 'Ističe',
    'Search codes...' => 'Pretraži kodove...',
    'All Statuses' => 'Svi Statusi',
    'Bulk Actions' => 'Grupne Akcije',
    'No codes found' => 'Nije pronađen nijedan kod',
    'Type to search...' => 'Kucaj za pretragu...',
    'Filter by category:' => 'Filtriraj po kategoriji:',
    'All categories' => 'Sve kategorije',
    'Sort by:' => 'Sortiraj po:',
    'Popularity' => 'Popularnost',
    
    // Package Configuration
    'Select between %d and %d products from our curated selection. The more you add, the more you save!' => 'Izaberi između %d i %d proizvoda iz našeg kuriranog izbora. Što više dodaš, više uštediš!',
    'VIP members get additional discounts on all packages!' => 'VIP članovi dobijaju dodatne popuste na sve pakete!',
    'Learn more' => 'Saznaj više',
    'Select your preferred package size to see available products and pricing.' => 'Izaberi željenu veličinu paketa da vidiš dostupne proizvode i cene.',
    'You have reached the maximum number of products for this package size.' => 'Dostigao si maksimalan broj proizvoda za ovu veličinu paketa.',
    'Please select at least one product.' => 'Molimo te da izabereš najmanje jedan proizvod.',
    'Select %d more products to complete your package' => 'Izaberi još %d proizvoda da završiš svoj paket',
    'Package complete! Click continue to proceed.' => 'Paket završen! Klikni nastavi da nastaviš.',
    'Select products to see your package total' => 'Izaberi proizvode da vidiš ukupnu cenu paketa',
    'Selected Products' => 'Izabrani Proizvodi',
    'Pricing Breakdown' => 'Razbivka Cena',
    
    // Display Options
    'Show both regular and VIP prices' => 'Prikaži i redovne i VIP cene', 
    'Show regular price only' => 'Prikaži samo redovnu cenu',
    'Show VIP price as teaser' => 'Prikaži VIP cenu kao najavu',
    'Enable' => 'Uključi'
];

echo "Prevod je kreiran. Koristiti language fajlove za automatske prevode.\n";
?>